### ISSUE TITLE
[DISCUSSION] Using hyprctl descriptions?

### ISSUE THREAD

**Issue by luyu-wu** [hyprutils/hyprgui#71]
Hey there! Just saw this project a while ago.

Looking at the codebase, hyprgui maintains it's own table of all configuration settings.
Would it be preferable to use hyprctl descriptions? 

The main advantages I can see is that this way the project will require less maintenance as new features are added to Hyprland and default (unset) configuration settings will also be correctly detected by the software.

If this is agreed to be best, I'd be willing to implement this (should just be a JSON parser + a bit of refactoring).

**Comment by nnyyxxxx** [comment]
https://github.com/hyprutils/hyprgui/pull/56

Was already accomplished here, the problem with auto generating entries is that you cannot have a good looking ui at that same time. That's why I decided against it, you would still have to manually group entries into the headers and there are way too many problems with that; also on that matter: hyprctl descriptions doesn't use standard Json, regex had to be implemented to cover this matter.

If new options get added to hyprctl descriptions then we will have to manually group these into headers, we would be at the mercy of the hyprland maintainers at that point. It's not really feasible with doing releases and other packaging, It's best it stays how it is right now.

If you have any better implementations I'd like to see them.

**Comment by luyu-wu** [comment]
I see! Sorry I didn't spot your dead PR before posting.

While doing a new implementation (maybe I could merge a PR into Hyprland?) sounds like a fun project, it also is significantly more effort and I need to focus on school for my senior year...

I'll close this issue for now and hopefully come back later to try and implement something!
